Add devise gem for authentication
yuliatokaryk/ask-me pull request #2
Opened 2022-10-18 07:29 UTC by yuliatokaryk

2022-11-11 15:10 UTC, ihortok requested changes

2022-11-11 15:10 UTC, ihortok commented on config/routes.rb
> +  devise_for :models
why model?

2022-11-11 15:10 UTC, ihortok commented on app/models/model.rb
> +class Model < ApplicationRecord
why model?

2022-11-12 09:19 UTC, yuliatokaryk commented on app/models/model.rb
> +class Model < ApplicationRecord
117e651fcf89600c86a39ac33fe777b44474cae1

2022-11-12 09:19 UTC, yuliatokaryk commented on config/routes.rb
> +  devise_for :models
117e651fcf89600c86a39ac33fe777b44474cae1

2022-11-12 12:00 UTC, ihortok approved these changes

2022-11-12 12:06 UTC, merged